package com.example.brokerportal.quoteservice.enums;

public enum AuditAction {
    QUOTE_CREATED,
    QUOTE_UPDATED,
    QUOTE_SOFT_DELETED,
    QUOTE_RESTORED,
    QUOTE_BOUND,

    CYBER_INSURANCE_CREATED,
    CYBER_INSURANCE_UPDATED,
    CYBER_INSURANCE_SOFT_DELETED,

    PROPERTY_INSURANCE_CREATED,
    PROPERTY_INSURANCE_UPDATED,
    PROPERTY_INSURANCE_SOFT_DELETED,

    GENERAL_INSURANCE_CREATED,
    GENERAL_INSURANCE_UPDATED,
    GENERAL_INSURANCE_SOFT_DELETED,

    PREMIUM_CALCULATED,
    PREMIUM_UPDATED,

    COVERAGE_ADDED,
    COVERAGE_UPDATED,
    COVERAGE_REMOVED,

    QUOTE_STATUS_CHANGED
}

